services:
  # Build statically with Sveltekit
  frontend:
    build:
      context: ./frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  # Backend with Apache server for PHP
  backend:
    build:
      context: ./backend
    networks:
      - tangointheworld-network
    hostname: tango-backend
    ports:
      - 80:80
    volumes:
      - ./backend:/var/www/html
    env_file:
      - .env

  # MySQL database
  database:
    build:
      context: ./database
    command: --authentication-policy=mysql_native_password
    networks:
      - tangointheworld-network
    hostname: tango-database
    ports:
      - 3306:3306
    env_file:
      - .env

# Networks to allow communication between containers
networks:
  tangointheworld-network:
    driver: bridge
